---

- name: Install etcd
  become: True
  package:
    name: etcd-server
    state: present

- name: Configure etcd
  become: True
  template:
    src: etcd.j2
    dest: /etc/default/etcd
    owner: root
    group: root
    mode: 0640
  notify: Restart etcd

- name: Start etcd
  service:
    name: etcd
    state: started
