---

- name: Install etcd
  become: True
  package:
    name: etcd-server
    state: present

- name: Configure etcd
  become: True
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - src: etcd.j2
      dest: /etc/default/etcd
    - src: systemd.service.j2
      dest: /etc/systemd/system/etcd.service
  notify: Restart etcd

- name: Start etcd
  become: True
  service:
    name: etcd
    state: started
    enabled: True
